openapi: 3.0.3
info:
  title: Football Competition Management API
  version: 1.0.0

paths:
  /competitions:
    post:
      summary: Create a new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompetitionInput'
      responses:
        '201':
          description: Competition created
    get:
      summary: Get a list of competitions
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of competitions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCompetitions'

  /teams:
    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamInput'
      responses:
        '201':
          description: Team created
    get:
      summary: Get a list of teams
      parameters:
        - in: query
          name: teamName
          schema:
            type: string
        - in: query
          name: page
          required: true
          schema:
            type: integer
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of teams
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTeams'

  /teams/{teamId}/players:
    post:
      summary: Add players to a team
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerInput'
      responses:
        '201':
          description: Player(s) added
    get:
      summary: Get a list of players in a team
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
        - in: query
          name: playerName
          schema:
            type: string
        - in: query
          name: page
          required: true
          schema:
            type: integer
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of players
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPlayers'

components:
  schemas:
    CompetitionInput:
      type: object
      properties:
        name:
          type: string
        location:
          type: string
      required:
        - name
        - location

    TeamInput:
      type: object
      properties:
        name:
          type: string
        slogan:
          type: string
      required:
        - name
        - slogan

    PlayerInput:
      type: object
      properties:
        name:
          type: string
        number:
          type: integer
        strongFoot:
          type: string
          enum:
            - Left
            - Right
      required:
        - name
        - number
        - strongFoot

    PaginatedCompetitions:
      type: object
      properties:
        competitions:
          type: array
          items:
            $ref: '#/components/schemas/CompetitionInput'
        page:
          type: integer
        pageSize:
          type: integer
        totalItems:
          type: integer
        totalPages:
          type: integer

    PaginatedTeams:
      type: object
      properties:
        teams:
          type: array
          items:
            $ref: '#/components/schemas/TeamInput'
        page:
          type: integer
        pageSize:
          type: integer
        totalItems:
          type: integer
        totalPages:
          type: integer

    PaginatedPlayers:
      type: object
      properties:
        players:
          type: array
          items:
            $ref: '#/components/schemas/PlayerInput'
        page:
          type: integer
        pageSize:
          type: integer
        totalItems:
          type: integer
        totalPages:
          type: integer
